# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
os:
  - linux
  - osx
cache: packages
warnings_are_errors: true
r:
  - release
r_binary_packages:
  - httr
  - dplyr
  - purrr
  - jsonlite
  - stringi
after_success:
  - Rscript -e 'covr::codecov()'
